#server:#  tomcat:#    basedir: C:/OurShefTestFoleder      server:      
  servlet:    session:      tracking-modes: cookie      timeout: 1800 #기본은 1800초(30분), 60초보다 작은 값은 설정 불가      
spring:
  messages:
    basename: errors

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/myShefDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: 1234
    username: shef
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true

        
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    open-in-view: false
       

logging:
  level:
   org.hibernate.SQL: debug
  
  
file:
  dir: C:/OurShefTestFoleder/