#server:#  tomcat:#    basedir: C:/OurShefTestFoleder      server:      
  servlet:    session:      tracking-modes: cookie      timeout: 1800 #기본은 1800초(30분), 60초보다 작은 값은 설정 불가      
spring:
  messages:
    basename: errors

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/myShefDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: 1234
    username: shef
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true

        
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    open-in-view: false
       

logging:
  level:
   org.hibernate.SQL: debug
  
  
file:
  dir:     userProfileImg: C:/OurShefUserProfileImg/    spotMainImg: C:/OurShefSpotMainImg/    spotAddedImg: C:/OurShefSpotAddedImg/    testImg: C:/OurShefTestImg/# It is injected from the Img controller, # but when there is no img by javascript in the client, # the logo in resources is directly requested without going through the controller, # so it is not the path used in the current version.      file:      demoImg: C:/OurShefDemoImg/shefmark.png